version: "3"

services:
  postgres:
    image: postgres:14.4
    restart: always
    logging:
      driver: "none"
    env_file:
      - ./docker/pg-variables.env

  service:
    build: ./app
    entrypoint: /opt/app/docker-entrypoint.sh
    depends_on:
      - postgres
    volumes:
      - ./static:/var/www
    expose:
      - "8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
    logging:
      driver: "none"

  nginx:
    image: nginx:1.23.0
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./log:/var/log/nginx
      - ./static:/var/www
    depends_on:
      - service
    ports:
      - "80:80"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    expose:
      - "9200"
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    logging:
      driver: "none"

  etl:
    build: ./etl
    environment:
      - FILE_STATE_PATH=./local_storage/local_state.json
      - ELASTIC_URI=http://es:9200/
    env_file:
      - ./docker/pg-variables.env
    command: /opt/etl/docker-entrypoint.sh
    depends_on:
      - es
      - service
      - postgres

  cache:
    image: redis:6.2-alpine
    restart: always

  search_api:
    build: ./search_api
    environment:
      - ELASTIC_HOST=es
      - ELASTIC_PORT=9200
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    logging:
      driver: "none"
    depends_on:
      - postgres
      - etl
      - es
      - cache

  tests:
    build: ./tests
    entrypoint: /opt/tests/docker-entrypoint.sh
    depends_on:
      - search_api
      - cache
      - es


